### PR TITLE
Some small type corrections

### PR DESCRIPTION
**Pull request by hammermaps**
Hello Sam, 
I'm working on some small corrections, can you use them?

### CODE REVIEW

**Comment by hammermaps** [comment]
Can I split some entities into separate files?
Like you did with HLEnhanced.
(https://github.com/SamVanheer/HLEnhanced/tree/master/game/server/entities/NPCs)

**Comment by SamVanheer** [comment]
You shouldn't be getting implicit conversion warnings when using MSVC since those warnings are disabled:
https://github.com/SamVanheer/halflife-unified-sdk/blob/9496a9f710682c04384e03bdc89825663fdc53b8/src/common/Platform.h#L29-L36

If you're getting them anyway then we'll need to look into disabling them. Fixing them isn't useful. A whole lot of code relies on those warnings being disabled.

Those commands should be moved to the main CMakeLists.txt along with GCC/Clang equivalents to normalize warnings, i'll look into that later.

CGenericItem doesn't need save/restore. `m_lastTime` isn't used and `m_iSequence` can be slightly reworked to avoid any chance of it being read after a restore.

> Can I split some entities into separate files?
> Like you did with HLEnhanced.

No. That was done to make it easier to implement code generation, but i've experimented with that in EnhancedHalfLife and it didn't work out. It dramatically increases compile times on its own because each source file needs to be compiled entirely separately so shared code is processed multiple times and code generation increases compile times even more.

Some code will be put into its own header file to make it easier to split up groups of classes and code into their own files but not one file per class.

Removal of unused variables and unnecessary casts is good, that can be kept.

**Comment by hammermaps** [comment]
Thanks, I will keep looking for unused variables and unnecessary casts.

**Comment by SamVanheer** [comment]
It might be easier to split this into new pull requests since it currently has a lot of commits that don't end up doing anything.

**Comment by hammermaps** [comment]
No problem, I will do it.

**Pull request closed without merging**
