### PR TITLE
Fix Linux build

### PR DESCRIPTION
**Pull request by JoelTroch**
This PR is a draft because I still need to figure out why CMake is not finding `vgui.so` and `libSDL2-2.0.so.0` when linking them to `client.so`. A dirty workaround is to manually copy them in yhe `build/game/client` directory.

### CODE REVIEW

**Comment by SamVanheer** [comment]
The change you made is incorrect because the `name` object is a  `string_view`. `The string returned by `.data()` is not guaranteed to be null-terminated, and it can point to a substring inside another, larger string.

Heterogeneous container lookup should allow the use of `string_view` here, so if it's a problem then you may be using an older version of GCC that doesn't support that yet.

The compiler should be finding the Linux libraries at the root of the binary directory because they're put here:
https://github.com/SamVanheer/halflife-unified-sdk/blob/2ca81f1497fb0ea98d70e66ebf93923603991f1e/src/game/client/CMakeLists.txt#L3-L8

They're put there precisely to ensure that the path to those libraries is a relative path, just like they are in the original SDK's Linux Makefiles.

If that's not working then there must be some discrepancy between my Linux setup and yours. I haven't run a Linux build in a few months so i'll have to check to see if it's still working on my end.

Can you post what your Linux environment is like (distro, version, GCC version)?

Also post the exact error messages you're getting, and which tool is giving them.

**Comment by SamVanheer** [comment]
My Linux setup also fails to compile the current master branch, the last test was before i used any heterogeneous lookup functionality. This was with GCC version 9.3.0.

I've installed GCC 11 using this as a guide: https://stackoverflow.com/a/67453352

This will install GCC 11 and update references to GCC to use it. Note the comments on the answer which address potential problems with the setting up of alternatives.

You'll also need to install required secondary packages in order to cross-compile to 32 bit on a 64 bit system: https://stackoverflow.com/questions/4643197/missing-include-bits-cconfig-h-when-cross-compiling-64-bit-program-on-32-bit

In this case the command will be this:
`sudo apt-get install gcc-11-multilib g++-11-multilib`

GCC 9.3.0 does not support C++20 and so cannot be used to compile this codebase.

I'll need to write up a complete guide for compiling this project on Linux later on.

**Comment by SamVanheer** [comment]
I've just done a complete build of both Half-Life Updated CMake and this project. The other project finds the libraries just fine, but this one doesn't. I guess the inclusion of the third party libraries is affecting the way GCC is looking up the libraries. I'll have to look into this further to see where the libraries need to go now.

**Comment by JoelTroch** [comment]
Thank you for the explanations and taking the time to look at this in-depth 😃 

>Can you post what your Linux environment is like (distro, version, GCC version)?

Ubuntu 20.04.2 LTS - GCC/G++ 9.3.0 Multilib. I made the switch to GCC/G++ 11 and removed the `.data()` part in the code, I'm now in the same situation as you where the code compiles but the linking of SDL2 and VGUI still fails on the client.

I applied the toolchain changes for PR #218 minus the "update alternatives" part, forcing `CC` and `CXX` to the proper GCC/G++ versions was enough. I avoided overriding `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` on purpose to prevent caching issues.

I'll update this PR if I find anything on my end.

**Comment by JoelTroch** [comment]
Closing this PR, fixed by `104ad2ee51c44d51bf7d991b039d91d44ca30f3e`

**Comment by SamVanheer** [comment]
Apparently i'd forgotten about the libraries i left in there during testing of that stuff. If you have both libraries located in both the root binary directory as well as the client makefile's directory it'll work. If you only have them in the root it'll find the files but fail to link, if you only have them in the makefile directory it'll fail to find them but would link correctly otherwise.

To fix this without copying files twice (i don't want any bugs resulting from two distinct files being involved) i've added some CMake hackery so a single set of files will satisfy both compilation stages. The files are now located in the client makefile directory (where they should be, the root directory path shouldn't be explicitly used in CMake projects) and a link directory points to that directory so that the linker will find the files as well.

The filenames embedded in the resulting client.so are lacking directories as they should be so they will be found in the root game directory as specified by `LD_LIBRARY_PATH` when run through Steam or when running standalone (which requires setting that variable to that directory).

I've committed the fix in https://github.com/SamVanheer/halflife-updated-cmake, and i've merged it into this repository now as well.

The fixes are in this commit:
https://github.com/SamVanheer/halflife-unified-sdk/commit/104ad2ee51c44d51bf7d991b039d91d44ca30f3e

Note that there are issues linking with other third party libraries preventing the client from successfully linking.

**Pull request closed without merging**
